/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "app-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gtk.GDBus.TestInterface
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:trainingapplication
 * @title: trainingapplication
 * @short_description: Generated C code for the org.gtk.GDBus.TestInterface D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gtk-GDBus-TestInterface.top_of_page">org.gtk.GDBus.TestInterface</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gtk.GDBus.TestInterface ---- */

static const _ExtendedGDBusArgInfo _training_application__method_info_set_time_IN_ARG_hourTime =
{
  {
    -1,
    (gchar *) "hourTime",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _training_application__method_info_set_time_IN_ARG_minTime =
{
  {
    -1,
    (gchar *) "minTime",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _training_application__method_info_set_time_IN_ARG_pointers[] =
{
  &_training_application__method_info_set_time_IN_ARG_hourTime.parent_struct,
  &_training_application__method_info_set_time_IN_ARG_minTime.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _training_application__method_info_set_time =
{
  {
    -1,
    (gchar *) "setTime",
    (GDBusArgInfo **) &_training_application__method_info_set_time_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-time",
  FALSE
};

static const _ExtendedGDBusArgInfo _training_application__method_info_set_alarm_time_IN_ARG_hourAlarmTime =
{
  {
    -1,
    (gchar *) "hourAlarmTime",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _training_application__method_info_set_alarm_time_IN_ARG_minAlarmTime =
{
  {
    -1,
    (gchar *) "minAlarmTime",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _training_application__method_info_set_alarm_time_IN_ARG_pointers[] =
{
  &_training_application__method_info_set_alarm_time_IN_ARG_hourAlarmTime.parent_struct,
  &_training_application__method_info_set_alarm_time_IN_ARG_minAlarmTime.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _training_application__method_info_set_alarm_time =
{
  {
    -1,
    (gchar *) "setAlarmTime",
    (GDBusArgInfo **) &_training_application__method_info_set_alarm_time_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-alarm-time",
  FALSE
};

static const _ExtendedGDBusArgInfo _training_application__method_info_get_alarm_status_OUT_ARG_alarmStatus =
{
  {
    -1,
    (gchar *) "alarmStatus",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _training_application__method_info_get_alarm_status_OUT_ARG_pointers[] =
{
  &_training_application__method_info_get_alarm_status_OUT_ARG_alarmStatus.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _training_application__method_info_get_alarm_status =
{
  {
    -1,
    (gchar *) "getAlarmStatus",
    NULL,
    (GDBusArgInfo **) &_training_application__method_info_get_alarm_status_OUT_ARG_pointers,
    NULL
  },
  "handle-get-alarm-status",
  FALSE
};

static const _ExtendedGDBusArgInfo _training_application__method_info_set_alarm_status_IN_ARG_alarmStatus =
{
  {
    -1,
    (gchar *) "alarmStatus",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _training_application__method_info_set_alarm_status_IN_ARG_pointers[] =
{
  &_training_application__method_info_set_alarm_status_IN_ARG_alarmStatus.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _training_application__method_info_set_alarm_status =
{
  {
    -1,
    (gchar *) "setAlarmStatus",
    (GDBusArgInfo **) &_training_application__method_info_set_alarm_status_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-alarm-status",
  FALSE
};

static const GDBusMethodInfo * const _training_application__method_info_pointers[] =
{
  &_training_application__method_info_set_time.parent_struct,
  &_training_application__method_info_set_alarm_time.parent_struct,
  &_training_application__method_info_get_alarm_status.parent_struct,
  &_training_application__method_info_set_alarm_status.parent_struct,
  NULL
};

static const _ExtendedGDBusArgInfo _training_application__signal_info_ring_alarm_ARG_messages =
{
  {
    -1,
    (gchar *) "messages",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _training_application__signal_info_ring_alarm_ARG_pointers[] =
{
  &_training_application__signal_info_ring_alarm_ARG_messages.parent_struct,
  NULL
};

static const _ExtendedGDBusSignalInfo _training_application__signal_info_ring_alarm =
{
  {
    -1,
    (gchar *) "ringAlarm",
    (GDBusArgInfo **) &_training_application__signal_info_ring_alarm_ARG_pointers,
    NULL
  },
  "ring-alarm"
};

static const GDBusSignalInfo * const _training_application__signal_info_pointers[] =
{
  &_training_application__signal_info_ring_alarm.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _training_application__interface_info =
{
  {
    -1,
    (gchar *) "org.gtk.GDBus.TestInterface",
    (GDBusMethodInfo **) &_training_application__method_info_pointers,
    (GDBusSignalInfo **) &_training_application__signal_info_pointers,
    NULL,
    NULL
  },
  "",
};


/**
 * training_application__interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gtk-GDBus-TestInterface.top_of_page">org.gtk.GDBus.TestInterface</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
training_application__interface_info (void)
{
  return (GDBusInterfaceInfo *) &_training_application__interface_info.parent_struct;
}

/**
 * training_application__override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #trainingapplication interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
training_application__override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * trainingapplication:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-TestInterface.top_of_page">org.gtk.GDBus.TestInterface</link>.
 */

/**
 * trainingapplicationIface:
 * @parent_iface: The parent interface.
 * @handle_get_alarm_status: Handler for the #trainingapplication::handle-get-alarm-status signal.
 * @handle_set_alarm_status: Handler for the #trainingapplication::handle-set-alarm-status signal.
 * @handle_set_alarm_time: Handler for the #trainingapplication::handle-set-alarm-time signal.
 * @handle_set_time: Handler for the #trainingapplication::handle-set-time signal.
 * @ring_alarm: Handler for the #trainingapplication::ring-alarm signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-TestInterface.top_of_page">org.gtk.GDBus.TestInterface</link>.
 */

typedef trainingapplicationIface trainingapplicationInterface;
G_DEFINE_INTERFACE (trainingapplication, training_application_, G_TYPE_OBJECT)

static void
training_application__default_init (trainingapplicationIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * trainingapplication::handle-set-time:
   * @object: A #trainingapplication.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_hourTime: Argument passed by remote caller.
   * @arg_minTime: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setTime">setTime()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call training_application__complete_set_time() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-time",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (trainingapplicationIface, handle_set_time),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT, G_TYPE_INT);

  /**
   * trainingapplication::handle-set-alarm-time:
   * @object: A #trainingapplication.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_hourAlarmTime: Argument passed by remote caller.
   * @arg_minAlarmTime: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmTime">setAlarmTime()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call training_application__complete_set_alarm_time() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-alarm-time",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (trainingapplicationIface, handle_set_alarm_time),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT, G_TYPE_INT);

  /**
   * trainingapplication::handle-get-alarm-status:
   * @object: A #trainingapplication.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.getAlarmStatus">getAlarmStatus()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call training_application__complete_get_alarm_status() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-alarm-status",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (trainingapplicationIface, handle_get_alarm_status),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * trainingapplication::handle-set-alarm-status:
   * @object: A #trainingapplication.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_alarmStatus: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmStatus">setAlarmStatus()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call training_application__complete_set_alarm_status() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-alarm-status",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (trainingapplicationIface, handle_set_alarm_status),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * trainingapplication::ring-alarm:
   * @object: A #trainingapplication.
   * @arg_messages: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-gtk-GDBus-TestInterface.ringAlarm">"ringAlarm"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("ring-alarm",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (trainingapplicationIface, ring_alarm),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRV);

}

/**
 * training_application__emit_ring_alarm:
 * @object: A #trainingapplication.
 * @arg_messages: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-gtk-GDBus-TestInterface.ringAlarm">"ringAlarm"</link> D-Bus signal.
 */
void
training_application__emit_ring_alarm (
    trainingapplication *object,
    const gchar *const *arg_messages)
{
  g_signal_emit_by_name (object, "ring-alarm", arg_messages);
}

/**
 * training_application__call_set_time:
 * @proxy: A #trainingapplicationProxy.
 * @arg_hourTime: Argument to pass with the method invocation.
 * @arg_minTime: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setTime">setTime()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call training_application__call_set_time_finish() to get the result of the operation.
 *
 * See training_application__call_set_time_sync() for the synchronous, blocking version of this method.
 */
void
training_application__call_set_time (
    trainingapplication *proxy,
    gint arg_hourTime,
    gint arg_minTime,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setTime",
    g_variant_new ("(ii)",
                   arg_hourTime,
                   arg_minTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * training_application__call_set_time_finish:
 * @proxy: A #trainingapplicationProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to training_application__call_set_time().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with training_application__call_set_time().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_set_time_finish (
    trainingapplication *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__call_set_time_sync:
 * @proxy: A #trainingapplicationProxy.
 * @arg_hourTime: Argument to pass with the method invocation.
 * @arg_minTime: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setTime">setTime()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See training_application__call_set_time() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_set_time_sync (
    trainingapplication *proxy,
    gint arg_hourTime,
    gint arg_minTime,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setTime",
    g_variant_new ("(ii)",
                   arg_hourTime,
                   arg_minTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__call_set_alarm_time:
 * @proxy: A #trainingapplicationProxy.
 * @arg_hourAlarmTime: Argument to pass with the method invocation.
 * @arg_minAlarmTime: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmTime">setAlarmTime()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call training_application__call_set_alarm_time_finish() to get the result of the operation.
 *
 * See training_application__call_set_alarm_time_sync() for the synchronous, blocking version of this method.
 */
void
training_application__call_set_alarm_time (
    trainingapplication *proxy,
    gint arg_hourAlarmTime,
    gint arg_minAlarmTime,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setAlarmTime",
    g_variant_new ("(ii)",
                   arg_hourAlarmTime,
                   arg_minAlarmTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * training_application__call_set_alarm_time_finish:
 * @proxy: A #trainingapplicationProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to training_application__call_set_alarm_time().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with training_application__call_set_alarm_time().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_set_alarm_time_finish (
    trainingapplication *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__call_set_alarm_time_sync:
 * @proxy: A #trainingapplicationProxy.
 * @arg_hourAlarmTime: Argument to pass with the method invocation.
 * @arg_minAlarmTime: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmTime">setAlarmTime()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See training_application__call_set_alarm_time() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_set_alarm_time_sync (
    trainingapplication *proxy,
    gint arg_hourAlarmTime,
    gint arg_minAlarmTime,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setAlarmTime",
    g_variant_new ("(ii)",
                   arg_hourAlarmTime,
                   arg_minAlarmTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__call_get_alarm_status:
 * @proxy: A #trainingapplicationProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.getAlarmStatus">getAlarmStatus()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call training_application__call_get_alarm_status_finish() to get the result of the operation.
 *
 * See training_application__call_get_alarm_status_sync() for the synchronous, blocking version of this method.
 */
void
training_application__call_get_alarm_status (
    trainingapplication *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getAlarmStatus",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * training_application__call_get_alarm_status_finish:
 * @proxy: A #trainingapplicationProxy.
 * @out_alarmStatus: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to training_application__call_get_alarm_status().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with training_application__call_get_alarm_status().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_get_alarm_status_finish (
    trainingapplication *proxy,
    gchar **out_alarmStatus,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_alarmStatus);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__call_get_alarm_status_sync:
 * @proxy: A #trainingapplicationProxy.
 * @out_alarmStatus: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.getAlarmStatus">getAlarmStatus()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See training_application__call_get_alarm_status() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_get_alarm_status_sync (
    trainingapplication *proxy,
    gchar **out_alarmStatus,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getAlarmStatus",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_alarmStatus);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__call_set_alarm_status:
 * @proxy: A #trainingapplicationProxy.
 * @arg_alarmStatus: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmStatus">setAlarmStatus()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call training_application__call_set_alarm_status_finish() to get the result of the operation.
 *
 * See training_application__call_set_alarm_status_sync() for the synchronous, blocking version of this method.
 */
void
training_application__call_set_alarm_status (
    trainingapplication *proxy,
    const gchar *arg_alarmStatus,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setAlarmStatus",
    g_variant_new ("(s)",
                   arg_alarmStatus),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * training_application__call_set_alarm_status_finish:
 * @proxy: A #trainingapplicationProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to training_application__call_set_alarm_status().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with training_application__call_set_alarm_status().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_set_alarm_status_finish (
    trainingapplication *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__call_set_alarm_status_sync:
 * @proxy: A #trainingapplicationProxy.
 * @arg_alarmStatus: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmStatus">setAlarmStatus()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See training_application__call_set_alarm_status() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
training_application__call_set_alarm_status_sync (
    trainingapplication *proxy,
    const gchar *arg_alarmStatus,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setAlarmStatus",
    g_variant_new ("(s)",
                   arg_alarmStatus),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * training_application__complete_set_time:
 * @object: A #trainingapplication.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setTime">setTime()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
training_application__complete_set_time (
    trainingapplication *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * training_application__complete_set_alarm_time:
 * @object: A #trainingapplication.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmTime">setAlarmTime()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
training_application__complete_set_alarm_time (
    trainingapplication *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * training_application__complete_get_alarm_status:
 * @object: A #trainingapplication.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @alarmStatus: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.getAlarmStatus">getAlarmStatus()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
training_application__complete_get_alarm_status (
    trainingapplication *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation,
    const gchar *alarmStatus)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   alarmStatus));
}

/**
 * training_application__complete_set_alarm_status:
 * @object: A #trainingapplication.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gtk-GDBus-TestInterface.setAlarmStatus">setAlarmStatus()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
training_application__complete_set_alarm_status (
    trainingapplication *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * trainingapplicationProxy:
 *
 * The #trainingapplicationProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * trainingapplicationProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #trainingapplicationProxy.
 */

struct _trainingapplicationProxyPrivate
{
  GData *qdata;
};

static void training_application__proxy_iface_init (trainingapplicationIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (trainingapplicationProxy, training_application__proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (trainingapplicationProxy)
                         G_IMPLEMENT_INTERFACE (TRAINING_APPLICATION_TYPE_, training_application__proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (trainingapplicationProxy, training_application__proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TRAINING_APPLICATION_TYPE_, training_application__proxy_iface_init))

#endif
static void
training_application__proxy_finalize (GObject *object)
{
  trainingapplicationProxy *proxy = TRAINING_APPLICATION__PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (training_application__proxy_parent_class)->finalize (object);
}

static void
training_application__proxy_get_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  GValue       *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
training_application__proxy_set_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
training_application__proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_training_application__interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TRAINING_APPLICATION_TYPE_);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TRAINING_APPLICATION_TYPE_);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
training_application__proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  trainingapplicationProxy *proxy = TRAINING_APPLICATION__PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_training_application__interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_training_application__interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
training_application__proxy_init (trainingapplicationProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = training_application__proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TRAINING_APPLICATION_TYPE__PROXY, trainingapplicationProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), training_application__interface_info ());
}

static void
training_application__proxy_class_init (trainingapplicationProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = training_application__proxy_finalize;
  gobject_class->get_property = training_application__proxy_get_property;
  gobject_class->set_property = training_application__proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = training_application__proxy_g_signal;
  proxy_class->g_properties_changed = training_application__proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (trainingapplicationProxyPrivate));
#endif
}

static void
training_application__proxy_iface_init (trainingapplicationIface *iface G_GNUC_UNUSED)
{
}

/**
 * training_application__proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-TestInterface.top_of_page">org.gtk.GDBus.TestInterface</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call training_application__proxy_new_finish() to get the result of the operation.
 *
 * See training_application__proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
training_application__proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TRAINING_APPLICATION_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.TestInterface", NULL);
}

/**
 * training_application__proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to training_application__proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with training_application__proxy_new().
 *
 * Returns: (transfer full) (type trainingapplicationProxy): The constructed proxy object or %NULL if @error is set.
 */
trainingapplication *
training_application__proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return TRAINING_APPLICATION_ (ret);
  else
    return NULL;
}

/**
 * training_application__proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-TestInterface.top_of_page">org.gtk.GDBus.TestInterface</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See training_application__proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type trainingapplicationProxy): The constructed proxy object or %NULL if @error is set.
 */
trainingapplication *
training_application__proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TRAINING_APPLICATION_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.TestInterface", NULL);
  if (ret != NULL)
    return TRAINING_APPLICATION_ (ret);
  else
    return NULL;
}


/**
 * training_application__proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like training_application__proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call training_application__proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See training_application__proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
training_application__proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TRAINING_APPLICATION_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.TestInterface", NULL);
}

/**
 * training_application__proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to training_application__proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with training_application__proxy_new_for_bus().
 *
 * Returns: (transfer full) (type trainingapplicationProxy): The constructed proxy object or %NULL if @error is set.
 */
trainingapplication *
training_application__proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return TRAINING_APPLICATION_ (ret);
  else
    return NULL;
}

/**
 * training_application__proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like training_application__proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See training_application__proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type trainingapplicationProxy): The constructed proxy object or %NULL if @error is set.
 */
trainingapplication *
training_application__proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TRAINING_APPLICATION_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.TestInterface", NULL);
  if (ret != NULL)
    return TRAINING_APPLICATION_ (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * trainingapplicationSkeleton:
 *
 * The #trainingapplicationSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * trainingapplicationSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #trainingapplicationSkeleton.
 */

struct _trainingapplicationSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_training_application__skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  trainingapplicationSkeleton *skeleton = TRAINING_APPLICATION__SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TRAINING_APPLICATION_TYPE_);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TRAINING_APPLICATION_TYPE_);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_training_application__skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  trainingapplicationSkeleton *skeleton = TRAINING_APPLICATION__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_training_application__interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_training_application__skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  trainingapplicationSkeleton *skeleton = TRAINING_APPLICATION__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_training_application__interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _training_application__skeleton_vtable =
{
  _training_application__skeleton_handle_method_call,
  _training_application__skeleton_handle_get_property,
  _training_application__skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
training_application__skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return training_application__interface_info ();
}

static GDBusInterfaceVTable *
training_application__skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_training_application__skeleton_vtable;
}

static GVariant *
training_application__skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  trainingapplicationSkeleton *skeleton = TRAINING_APPLICATION__SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_training_application__interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _training_application__interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _training_application__interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _training_application__skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gtk.GDBus.TestInterface", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
training_application__skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton G_GNUC_UNUSED)
{
}

static void
_training_application__on_signal_ring_alarm (
    trainingapplication *object,
    const gchar *const *arg_messages)
{
  trainingapplicationSkeleton *skeleton = TRAINING_APPLICATION__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(^as)",
                   arg_messages));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gtk.GDBus.TestInterface", "ringAlarm",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void training_application__skeleton_iface_init (trainingapplicationIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (trainingapplicationSkeleton, training_application__skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (trainingapplicationSkeleton)
                         G_IMPLEMENT_INTERFACE (TRAINING_APPLICATION_TYPE_, training_application__skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (trainingapplicationSkeleton, training_application__skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TRAINING_APPLICATION_TYPE_, training_application__skeleton_iface_init))

#endif
static void
training_application__skeleton_finalize (GObject *object)
{
  trainingapplicationSkeleton *skeleton = TRAINING_APPLICATION__SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (training_application__skeleton_parent_class)->finalize (object);
}

static void
training_application__skeleton_init (trainingapplicationSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = training_application__skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TRAINING_APPLICATION_TYPE__SKELETON, trainingapplicationSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
training_application__skeleton_class_init (trainingapplicationSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = training_application__skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = training_application__skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = training_application__skeleton_dbus_interface_get_properties;
  skeleton_class->flush = training_application__skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = training_application__skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (trainingapplicationSkeletonPrivate));
#endif
}

static void
training_application__skeleton_iface_init (trainingapplicationIface *iface)
{
  iface->ring_alarm = _training_application__on_signal_ring_alarm;
}

/**
 * training_application__skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-TestInterface.top_of_page">org.gtk.GDBus.TestInterface</link>.
 *
 * Returns: (transfer full) (type trainingapplicationSkeleton): The skeleton object.
 */
trainingapplication *
training_application__skeleton_new (void)
{
  return TRAINING_APPLICATION_ (g_object_new (TRAINING_APPLICATION_TYPE__SKELETON, NULL));
}

